# Firmware composition: owned PCI block and COM2 drivers, queue muxes and VMM.
[[pd]]
name = "virtio_blk"
priority = 215

[[pd]]
name = "blk_virt"
priority = 210

[[pd]]
name = "serial_pd"
priority = 180

[[pd]]
name = "serial_virt"
priority = 203

[[pd]]
name = "guest_vmm_primary"
priority = 250
