#!/usr/bin/env python3
"""
gen_channels.py — Generate channels_generated.h from agentos.system XML.

Usage:
    python3 tools/gen-channels/gen_channels.py

Reads:  kernel/agentos-root-task/agentos.system
Writes: kernel/agentos-root-task/include/channels_generated.h
"""

import os
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT   = os.path.normpath(os.path.join(SCRIPT_DIR, "..", ".."))
SYSTEM_XML  = os.path.join(REPO_ROOT, "kernel", "agentos-root-task", "agentos.system")
OUTPUT_H    = os.path.join(REPO_ROOT, "kernel", "agentos-root-task", "include", "channels_generated.h")
REL_SOURCE  = "kernel/agentos-root-task/agentos.system"


def sanitise(name: str) -> str:
    """Convert a PD name to an upper-case C identifier component."""
    return name.upper().replace("-", "_").replace(".", "_")


def main() -> None:
    if not os.path.isfile(SYSTEM_XML):
        print(f"ERROR: cannot find {SYSTEM_XML}", file=sys.stderr)
        sys.exit(1)

    tree = ET.parse(SYSTEM_XML)
    root = tree.getroot()

    # Collect per-PD channel ends: pd_name -> list of (end_id, other_pd_name)
    # Each <channel> has exactly two <end> elements.
    pd_channels: dict[str, list[tuple[int, str]]] = defaultdict(list)

    for channel in root.iter("channel"):
        ends = list(channel.iter("end"))
        if len(ends) != 2:
            continue  # malformed entry — skip
        pd_a = ends[0].get("pd", "")
        id_a = int(ends[0].get("id", "0"))
        pd_b = ends[1].get("pd", "")
        id_b = int(ends[1].get("id", "0"))

        pd_channels[pd_a].append((id_a, pd_b))
        pd_channels[pd_b].append((id_b, pd_a))

    # Sort by PD name for deterministic output, then by end id within each PD.
    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by tools/gen-channels/gen_channels.py — DO NOT EDIT */")
    lines.append(f"/* Source: {REL_SOURCE} */")
    lines.append("")
    lines.append("#ifndef AGENTOS_CHANNELS_GENERATED_H")
    lines.append("#define AGENTOS_CHANNELS_GENERATED_H")
    lines.append("")

    for pd_name in sorted(pd_channels.keys()):
        entries = sorted(pd_channels[pd_name], key=lambda x: x[0])
        enum_name = f"{sanitise(pd_name).lower()}_channel_t"
        lines.append(f"/* Channel IDs from {pd_name} perspective */")
        lines.append(f"typedef enum {{")

        # Count peer occurrences to disambiguate duplicate peer names.
        peer_count: dict[str, int] = defaultdict(int)
        for (_, peer) in entries:
            peer_count[sanitise(peer)] += 1

        peer_seen: dict[str, int] = defaultdict(int)
        for (end_id, peer) in entries:
            peer_key = sanitise(peer)
            if peer_count[peer_key] > 1:
                # Append a numeric suffix to disambiguate (0-based).
                suffix = f"_{peer_seen[peer_key]}"
                peer_seen[peer_key] += 1
            else:
                suffix = ""
            const_name = f"CH_{sanitise(pd_name)}_{peer_key}{suffix}"
            lines.append(f"    {const_name:<44} = {end_id},")

        lines.append(f"}} {enum_name};")
        lines.append("")

    lines.append("#endif /* AGENTOS_CHANNELS_GENERATED_H */")
    lines.append("")

    output = "\n".join(lines)
    os.makedirs(os.path.dirname(OUTPUT_H), exist_ok=True)
    with open(OUTPUT_H, "w") as f:
        f.write(output)

    print(f"Generated {OUTPUT_H}")
    print(f"  {len(pd_channels)} protection domains, "
          f"{sum(len(v) for v in pd_channels.values())} channel endpoints")


if __name__ == "__main__":
    main()
