#ifndef AOS_FRAMEBUFFER_ISOLATION_PROBE_H
#define AOS_FRAMEBUFFER_ISOLATION_PROBE_H
#include <platform/framebuffer_observer.h>
#ifdef AGENTOS_FRAMEBUFFER_ISOLATION_PROBE
#if AGENTOS_FRAMEBUFFER_ISOLATION_PROBE < 1 || AGENTOS_FRAMEBUFFER_ISOLATION_PROBE > 16
#error framebuffer isolation probe must be 1..16
#endif
#define AOS_FB_PROBE_CLIENT (((AGENTOS_FRAMEBUFFER_ISOLATION_PROBE - 1u) % 8u) / 4u)
#define AOS_FB_PROBE_WRITE ((AGENTOS_FRAMEBUFFER_ISOLATION_PROBE % 2u) == 0)
#define AOS_FB_PROBE_ARENA (((AGENTOS_FRAMEBUFFER_ISOLATION_PROBE - 1u) % 4u) >= 2u)
#define AOS_FB_PROBE_ADDRESS (AGENTOS_FRAMEBUFFER_ISOLATION_PROBE > 8 ? \
    (AOS_FB_PROBE_ARENA ? AOS_FB_SNAPSHOT_VA : AOS_FB_OBSERVER_VA) : \
    (AOS_FB_PROBE_ARENA ? AOS_FB_ARENA_VA : \
    AOS_FB_SHMEM_VA + (1u - AOS_FB_PROBE_CLIENT) * AOS_FB_CLIENT_STRIDE))
#define AOS_FB_PROBE_BADGE (0xa0570000u + AGENTOS_FRAMEBUFFER_ISOLATION_PROBE)
#define AOS_FB_PROBE_MESSAGE "[rt] framebuffer isolation: expected client data fault verified\n"
#endif
#endif
