#ifndef AOS_OPERATOR_ISOLATION_PROBE_H
#define AOS_OPERATOR_ISOLATION_PROBE_H
#include <platform/inspect.h>
#include <platform/serial_virt_layout.h>
#ifdef AGENTOS_OPERATOR_ISOLATION_PROBE
#if AGENTOS_OPERATOR_ISOLATION_PROBE < 1 || AGENTOS_OPERATOR_ISOLATION_PROBE > 7
#error "operator isolation probe must be 1..7"
#endif
#define AOS_OPERATOR_PROBE_BADGE (0xa0550000u + AGENTOS_OPERATOR_ISOLATION_PROBE)
#define AOS_OPERATOR_PROBE_WRITE ((AGENTOS_OPERATOR_ISOLATION_PROBE % 2) == 0 || AGENTOS_OPERATOR_ISOLATION_PROBE == 7)
#define AOS_OPERATOR_PROBE_PAGE ((AGENTOS_OPERATOR_ISOLATION_PROBE - 1) / 2)
#define AOS_OPERATOR_PROBE_ADDRESS (AGENTOS_OPERATOR_ISOLATION_PROBE == 7 ? AOS_INSPECT_BOOT_VA : \
    AOS_SERIAL_SHMEM_VA + (AOS_OPERATOR_PROBE_PAGE < 2 ? AOS_OPERATOR_PROBE_PAGE : AOS_SERIAL_FRONTEND_FRAME) * AOS_SERIAL_FRAME_SIZE)
#define AOS_OPERATOR_PROBE_MESSAGE "[rt] operator isolation: expected client data fault verified\n"
#endif
#endif
