use anyhow::{Context, Result};
use clap::Parser;
use serde::Deserialize;
use std::path::PathBuf;

// ── Serde structs ─────────────────────────────────────────────────────── //

#[derive(Deserialize)]
struct Schema {
    ring_name: String,
    entry_type: String,
    capacity: u32,
    fields: Vec<Field>,
    includes: Option<Vec<String>>,
    mr_vaddr_var: Option<String>,
}

#[derive(Deserialize)]
struct Field {
    name: String,
    #[serde(rename = "type")]
    ty: String,
    count: Option<u32>,
}

// ── Helpers ───────────────────────────────────────────────────────────── //

fn is_power_of_two(n: u32) -> bool {
    n > 0 && (n & (n - 1)) == 0
}

fn c_field_line(field: &Field) -> String {
    match field.count {
        Some(c) => format!("    {} {}[{}];", field.ty, field.name, c),
        None => format!("    {} {};", field.ty, field.name),
    }
}

fn struct_size_hint(fields: &[Field]) -> String {
    let known = |ty: &str| -> u64 {
        match ty {
            "uint8_t" | "int8_t" | "bool" => 1,
            "uint16_t" | "int16_t" => 2,
            "uint32_t" | "int32_t" | "float" => 4,
            "uint64_t" | "int64_t" | "double" => 8,
            _ => 0,
        }
    };
    let total: u64 = fields
        .iter()
        .map(|f| known(&f.ty) * f.count.unwrap_or(1) as u64)
        .sum();
    if total > 0 {
        format!("  // approx {} bytes", total)
    } else {
        String::new()
    }
}

// ── Validate ─────────────────────────────────────────────────────────── //

fn validate(schema: &Schema) -> Vec<String> {
    let mut errors: Vec<String> = Vec::new();

    if schema.ring_name.is_empty() {
        errors.push("Missing required field: ring_name".to_string());
    }
    if schema.entry_type.is_empty() {
        errors.push("Missing required field: entry_type".to_string());
    }
    if !is_power_of_two(schema.capacity) {
        errors.push(format!(
            "capacity must be a power of 2, got: {}",
            schema.capacity
        ));
    }
    if schema.fields.is_empty() {
        errors.push(
            "Missing required field: fields (must be non-empty list)".to_string(),
        );
    } else {
        for (i, f) in schema.fields.iter().enumerate() {
            if f.name.is_empty() {
                errors.push(format!("fields[{}]: missing 'name'", i));
            }
            if f.ty.is_empty() {
                errors.push(format!("fields[{}]: missing 'type'", i));
            }
        }
    }
    errors
}

// ── generate ─────────────────────────────────────────────────────────── //

fn generate(schema: &Schema, source_name: &str) -> String {
    let ring_name = &schema.ring_name;
    let entry_type = &schema.entry_type;
    let capacity = schema.capacity;
    let fields = &schema.fields;
    let includes = schema.includes.as_deref().unwrap_or(&[]);
    let mr_var = schema.mr_vaddr_var.as_deref();
    let guard = format!("{}_H", ring_name.to_uppercase());

    let mut lines: Vec<String> = Vec::new();
    lines.push(format!(
        "/* Generated by gen_ringbuf.py from: {} */",
        source_name
    ));
    lines.push(format!(
        "/* Do not edit — regenerate with: python3 tools/gen_ringbuf.py {} */",
        source_name
    ));
    lines.push(String::new());
    lines.push("#pragma once".to_string());
    lines.push(format!("#ifndef {}", guard));
    lines.push(format!("#define {}", guard));
    lines.push(String::new());
    lines.push(r#"#include "ringbuf.h""#.to_string());
    for inc in includes {
        lines.push(format!("#include {}", inc));
    }
    lines.push(String::new());

    // Entry struct
    let hint = struct_size_hint(fields);
    lines.push(format!(
        "/* Ring entry: {} {} */",
        entry_type,
        hint.trim()
    ));
    lines.push("typedef struct {".to_string());
    for f in fields {
        lines.push(c_field_line(f));
    }
    lines.push(format!("}} {};", entry_type));
    lines.push(String::new());

    // Ring type via RINGBUF_DEFINE
    lines.push(format!(
        "/* Ring type: {} (capacity={}) */",
        ring_name, capacity
    ));
    lines.push(format!(
        "RINGBUF_DEFINE({}, {}, {});",
        ring_name, entry_type, capacity
    ));
    lines.push(String::new());

    // Optional MR-bound helper wrappers
    if let Some(mr_var) = mr_var {
        let lower = ring_name.to_lowercase();
        lines.push(format!("/* Convenience helpers bound to {} */", mr_var));
        lines.push(format!("extern uintptr_t {};", mr_var));
        lines.push(String::new());
        lines.push(format!(
            "static inline {} *{}_get(void) {{",
            ring_name, lower
        ));
        lines.push(format!(
            "    return ({} *)(uintptr_t){};",
            ring_name, mr_var
        ));
        lines.push("}".to_string());
        lines.push(String::new());
        lines.push(format!(
            "static inline void {}_init_producer(void) {{",
            lower
        ));
        lines.push(format!(
            "    RINGBUF_INIT_PRODUCER({}_get());",
            lower
        ));
        lines.push("}".to_string());
        lines.push(String::new());
        lines.push(format!(
            "static inline void {}_init_consumer(void) {{",
            lower
        ));
        lines.push(format!(
            "    RINGBUF_INIT_CONSUMER({}_get());",
            lower
        ));
        lines.push("}".to_string());
        lines.push(String::new());
        lines.push(format!(
            "static inline bool {}_enqueue(const {} *e) {{",
            lower, entry_type
        ));
        lines.push(format!(
            "    return RINGBUF_ENQUEUE({}_get(), *e);",
            lower
        ));
        lines.push("}".to_string());
        lines.push(String::new());
        lines.push(format!(
            "static inline bool {}_dequeue({} *e) {{",
            lower, entry_type
        ));
        lines.push(format!(
            "    return RINGBUF_DEQUEUE({}_get(), e);",
            lower
        ));
        lines.push("}".to_string());
        lines.push(String::new());
    }

    lines.push(format!("#endif /* {} */", guard));
    lines.join("\n") + "\n"
}

// ── generate_test ────────────────────────────────────────────────────── //

fn generate_test(schema: &Schema) -> String {
    let ring_name = &schema.ring_name;
    let entry_type = &schema.entry_type;
    let capacity = schema.capacity;
    let lower = ring_name.to_lowercase();

    let mut lines: Vec<String> = Vec::new();
    lines.push(format!("/* Auto-generated test stub for {} */", ring_name));
    lines.push(format!(r#"#include "{}.h""#, lower));
    lines.push("#include <stdio.h>".to_string());
    lines.push("#include <assert.h>".to_string());
    lines.push("#include <string.h>".to_string());
    lines.push(String::new());
    lines.push(format!("static {} g_ring;", ring_name));
    lines.push(String::new());
    lines.push("int main(void) {".to_string());
    lines.push("    RINGBUF_INIT_PRODUCER(&g_ring);".to_string());
    lines.push("    assert(RINGBUF_VALID(&g_ring));".to_string());
    lines.push("    assert(RINGBUF_EMPTY(&g_ring));".to_string());
    lines.push("    assert(!RINGBUF_FULL(&g_ring));".to_string());
    lines.push(String::new());
    lines.push("    /* Fill ring to capacity */".to_string());
    lines.push(format!("    for (int i = 0; i < {}; i++) {{", capacity));
    lines.push(format!("        {} e;", entry_type));
    lines.push("        memset(&e, 0, sizeof(e));".to_string());
    lines.push("        assert(RINGBUF_TRY_ENQUEUE(&g_ring, e));".to_string());
    lines.push("    }".to_string());
    lines.push("    assert(RINGBUF_FULL(&g_ring));".to_string());
    lines.push(format!(
        "    assert(!RINGBUF_TRY_ENQUEUE(&g_ring, ({}){{0}}));",
        entry_type
    ));
    lines.push(String::new());
    lines.push("    /* Drain ring */".to_string());
    lines.push("    int dequeued = 0;".to_string());
    lines.push(format!("    {} out;", entry_type));
    lines.push(
        "    while (RINGBUF_DEQUEUE(&g_ring, &out)) dequeued++;".to_string(),
    );
    lines.push(format!("    assert(dequeued == {});", capacity));
    lines.push("    assert(RINGBUF_EMPTY(&g_ring));".to_string());
    lines.push(String::new());
    lines.push(format!(
        r#"    printf("{} test passed (capacity=%d)\n", {});"#,
        ring_name, capacity
    ));
    lines.push("    return 0;".to_string());
    lines.push("}".to_string());
    lines.join("\n") + "\n"
}

// ── CLI ───────────────────────────────────────────────────────────────── //

#[derive(Parser)]
#[command(name = "gen-ringbuf", about = "agentOS ring buffer code generator")]
struct Cli {
    /// YAML schema file
    schema: PathBuf,

    /// Output .h file (default: <ring_name>.h in same dir)
    #[arg(short, long)]
    output: Option<PathBuf>,

    /// Also emit a test stub <ring_name>_test.c
    #[arg(long)]
    test: bool,

    /// Validate schema and exit without writing files
    #[arg(long)]
    validate_only: bool,
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    let content = std::fs::read_to_string(&cli.schema)
        .with_context(|| format!("failed to read {}", cli.schema.display()))?;

    let schema: Schema = serde_yaml::from_str(&content)
        .with_context(|| "YAML parse error")?;

    let errors = validate(&schema);
    if !errors.is_empty() {
        for e in &errors {
            eprintln!("  ✗ {}", e);
        }
        std::process::exit(1);
    }

    if cli.validate_only {
        println!(
            "✓ Schema valid: {} / {} / capacity={}",
            schema.ring_name, schema.entry_type, schema.capacity
        );
        return Ok(());
    }

    let source_name = cli
        .schema
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("schema.yaml")
        .to_string();

    let code = generate(&schema, &source_name);

    let out_path = cli.output.unwrap_or_else(|| {
        let dir = cli
            .schema
            .parent()
            .unwrap_or_else(|| std::path::Path::new("."));
        dir.join(format!("{}.h", schema.ring_name.to_lowercase()))
    });

    std::fs::write(&out_path, &code)
        .with_context(|| format!("failed to write {}", out_path.display()))?;
    println!("✓ Generated: {}", out_path.display());

    if cli.test {
        let test_code = generate_test(&schema);
        let test_path = out_path.with_extension("").to_string_lossy().to_string() + "_test.c";
        let test_path = std::path::Path::new(&test_path).to_path_buf();
        // If out_path was .h, replace extension
        let test_path = if out_path.extension().and_then(|e| e.to_str()) == Some("h") {
            out_path
                .with_file_name(format!(
                    "{}_test.c",
                    out_path
                        .file_stem()
                        .and_then(|s| s.to_str())
                        .unwrap_or("ring")
                ))
        } else {
            test_path
        };
        std::fs::write(&test_path, &test_code)
            .with_context(|| format!("failed to write {}", test_path.display()))?;
        println!("✓ Test stub:  {}", test_path.display());
        println!(
            "  Compile with: gcc -std=c11 -I. {} -o test_{}",
            test_path.display(),
            schema.ring_name.to_lowercase()
        );
    }

    Ok(())
}

// ── Tests ─────────────────────────────────────────────────────────────── //

#[cfg(test)]
mod tests {
    use super::*;

    fn make_schema(ring_name: &str, entry_type: &str, capacity: u32, fields: Vec<Field>) -> Schema {
        Schema {
            ring_name: ring_name.to_string(),
            entry_type: entry_type.to_string(),
            capacity,
            fields,
            includes: None,
            mr_vaddr_var: None,
        }
    }

    fn field(name: &str, ty: &str) -> Field {
        Field {
            name: name.to_string(),
            ty: ty.to_string(),
            count: None,
        }
    }

    #[test]
    fn test_validate_capacity() {
        let schema = make_schema(
            "TestRing",
            "TestEntry",
            100, // not power of 2
            vec![field("x", "uint32_t")],
        );
        let errors = validate(&schema);
        assert!(
            errors.iter().any(|e| e.contains("power of 2")),
            "expected power-of-2 error, got: {:?}",
            errors
        );
    }

    #[test]
    fn test_generate_minimal() {
        let schema = make_schema(
            "MyRing",
            "MyEntry",
            64,
            vec![field("ts", "uint64_t"), field("val", "uint32_t")],
        );
        let errors = validate(&schema);
        assert!(errors.is_empty(), "should be valid: {:?}", errors);
        let output = generate(&schema, "test.yaml");
        assert!(
            output.contains("#pragma once"),
            "output should contain #pragma once"
        );
        assert!(
            output.contains("RINGBUF_DEFINE"),
            "output should contain RINGBUF_DEFINE"
        );
        assert!(
            output.contains("MyEntry"),
            "output should contain entry type"
        );
        assert!(
            output.contains("uint64_t ts;"),
            "output should contain ts field"
        );
    }

    #[test]
    fn test_generate_with_mr_var() {
        let schema = Schema {
            ring_name: "PerfRing".to_string(),
            entry_type: "PerfRecord".to_string(),
            capacity: 64,
            fields: vec![field("ts", "uint64_t")],
            includes: None,
            mr_vaddr_var: Some("perf_ring_vaddr".to_string()),
        };
        let errors = validate(&schema);
        assert!(errors.is_empty(), "should be valid: {:?}", errors);
        let output = generate(&schema, "perf.yaml");
        assert!(
            output.contains("perfring_get"),
            "output should contain _get() helper, got:\n{}",
            output
        );
        assert!(
            output.contains("perfring_enqueue"),
            "output should contain _enqueue() helper"
        );
        assert!(
            output.contains("perfring_dequeue"),
            "output should contain _dequeue() helper"
        );
    }
}
