/*
 * boot_info.h — seL4 BootInfo structure and supplementary types
 *
 * Extends sel4_boot.h with the seL4_BootInfo structure (received by the
 * root task at startup), seL4 object type constants not already defined
 * in sel4_boot.h, and the seL4_Yield() scheduler primitive.
 *
 * On a real seL4 build these come from <sel4/sel4.h> and
 * <sel4/bootinfo_types.h>.  This header provides equivalent standalone
 * definitions for the bare-metal root task that cannot link against
 * the full sel4 library.
 *
 * IMPORTANT: The slot-number constants here (seL4_NumInitialCaps, etc.)
 * follow the numbering used by this project's sel4_boot.h, which is a
 * simplified subset of the canonical seL4 values.  See DESIGN.md for the
 * mapping between this project's slots and real seL4 CNode indices.
 *
 * Copyright (c) 2026 The agentOS Project
 * SPDX-License-Identifier: BSD-2-Clause
 */

#pragma once

#include "sel4_boot.h"
#include <stdint.h>

/* ── Supplementary seL4 object type constants ─────────────────────────────── */

/*
 * seL4_CapTableObject — used to create CNodes (capability tables).
 * Value 3 matches the canonical seL4 objecttype.h enum.
 */
#ifndef seL4_CapTableObject
#define seL4_CapTableObject  3u
#endif

/*
 * ARM-specific object types.
 * seL4_ARM_VSpaceObject == PageGlobalDirectory (Aarch64) or PageDirectory.
 * seL4_ARM_SmallPageObject == 4 KB page frame.
 *
 * These match the enum values generated by the seL4 AArch64 kernel headers:
 *   seL4_ARM_VSpaceObject     = seL4_ModeObjectTypeCount + 1  (== 7)
 *   seL4_ARM_SmallPageObject  = seL4_ModeObjectTypeCount + 2  (== 8 on AArch64)
 *
 * For RISC-V the VSpace object is called seL4_RISCV_PageTableObject; we alias
 * seL4_ARM_VSpaceObject to the same numeric constant so main.c compiles on
 * both architectures without #ifdefs at every call site.
 *
 * Values are used only as hints to ut_alloc(); the kernel validates them.
 */
#ifndef seL4_ARM_VSpaceObject
#define seL4_ARM_VSpaceObject      7u
#endif
#ifndef seL4_ARM_SmallPageObject
#define seL4_ARM_SmallPageObject   8u
#endif
#ifndef seL4_ARM_Default_VMAttributes
#define seL4_ARM_Default_VMAttributes  0u
#endif
#ifndef seL4_ReadWrite
#define seL4_ReadWrite  3u
#endif

/* Total number of capability slots reserved by the kernel for well-known caps.
 * In this project's slot layout the boot caps occupy slots 1..8
 * (seL4_CapInitThreadCNode .. seL4_CapBootInfoFrame), so the first free slot
 * for the root task to use is 9.  We define seL4_NumInitialCaps accordingly.
 */
#ifndef seL4_NumInitialCaps
#define seL4_NumInitialCaps  9u
#endif

/* ── seL4_Yield ───────────────────────────────────────────────────────────── */

/*
 * seL4_Yield — yield the CPU to the next runnable thread.
 *
 * Implemented as an inline that emits the seL4_SysYield syscall directly
 * via inline assembly.  On AArch64 seL4 uses svc #0 with the syscall
 * number in x7; on RISC-V it uses ecall with the number in a7.
 *
 * The root task calls this in its idle loop after starting all PD threads.
 */
#if defined(__aarch64__)
static inline void seL4_Yield(void)
{
    /* seL4 AArch64: syscall number -5 (seL4_SysYield) in x7, svc #0 */
    register seL4_Word scno __asm__("x7") = (seL4_Word)(-5);
    __asm__ volatile("svc #0" : : "r"(scno) : "memory", "cc");
}
#elif defined(__riscv)
static inline void seL4_Yield(void)
{
    /* seL4 RISC-V: syscall number -5 in a7, ecall */
    register seL4_Word scno __asm__("a7") = (seL4_Word)(-5);
    __asm__ volatile("ecall" : : "r"(scno) : "memory");
}
#else
/* Fallback for host-side stub builds (simulator / test harness) */
static inline void seL4_Yield(void) { /* no-op */ }
#endif

/* ── seL4 BootInfo types ──────────────────────────────────────────────────── */

typedef seL4_Word seL4_SlotPos;

typedef struct {
    seL4_SlotPos start; /* first CNode slot of region (inclusive) */
    seL4_SlotPos end;   /* first CNode slot after region (exclusive) */
} seL4_SlotRegion;

typedef struct {
    seL4_Word  paddr;    /* physical base address of the untyped region */
    uint8_t    sizeBits; /* log2(size in bytes) of the untyped cap */
    uint8_t    isDevice; /* non-zero if this is device memory */
    uint8_t    padding[sizeof(seL4_Word) - 2 * sizeof(uint8_t)];
} seL4_UntypedDesc;

/*
 * Maximum untyped caps reported by the kernel.  Matches
 * CONFIG_MAX_NUM_BOOTINFO_UNTYPED_CAPS in real seL4 builds.
 * Sized conservatively for the target boards; the kernel will
 * report fewer entries in practice.
 */
#define SEL4_BOOTINFO_MAX_UNTYPED  230u

typedef struct {
    seL4_Word          extraLen;               /* length of supplemental boot info */
    seL4_Word          nodeID;                 /* multiprocessor node ID (0 if UP) */
    seL4_Word          numNodes;               /* total seL4 nodes (1 if UP)       */
    seL4_Word          numIOPTLevels;          /* IOMMU PT depth (0 = no IOMMU)    */
    void              *ipcBuffer;              /* pointer to root-task IPC buffer  */
    seL4_SlotRegion    empty;                  /* empty cap slots available        */
    seL4_SlotRegion    sharedFrames;           /* shared frame caps (SMP)          */
    seL4_SlotRegion    userImageFrames;        /* caps for root-task image pages   */
    seL4_SlotRegion    userImagePaging;        /* caps for root-task page tables   */
    seL4_SlotRegion    ioSpaceCaps;            /* ARM SMMU IO space caps           */
    seL4_SlotRegion    extraBIPages;           /* caps for extra BootInfo pages    */
    seL4_Word          initThreadCNodeSizeBits;/* root CNode radix (2^n slots)     */
    seL4_Word          initThreadDomain;       /* initial thread's scheduling domain */
    seL4_SlotRegion    untyped;                /* untyped-object caps              */
    seL4_UntypedDesc   untypedList[SEL4_BOOTINFO_MAX_UNTYPED]; /* untyped descriptors */
} seL4_BootInfo;

/* ── seL4 extra boot-info chunk header ────────────────────────────────────── */

typedef struct {
    seL4_Word id;  /* chunk type identifier (seL4_BootInfoID) */
    seL4_Word len; /* total length of this chunk, including this header */
} seL4_BootInfoHeader;

/* Chunk IDs for extra BootInfo regions embedded by the loader. */
#define SEL4_BOOTINFO_HEADER_PADDING  0u
#define SEL4_BOOTINFO_HEADER_FDT      6u   /* flattened device tree */
/* agentOS-specific extra region type: embedded PD ELF images */
#define AGENTOS_BOOTINFO_HEADER_ELF   0x4147u  /* 'AG' */

/* ── ELF region descriptor (agentOS extension) ────────────────────────────── */

/*
 * agentos_elf_region_t — describes one embedded PD ELF in the extra BootInfo.
 *
 * The loader (xtask gen-image) appends one of these headers immediately
 * before each embedded ELF blob.  The root task's boot_find_elf() helper
 * walks the extra region list to locate ELFs by name.
 */
typedef struct {
    char      pd_name[32]; /* NUL-terminated PD name (matches pd_desc_t.name) */
    seL4_Word elf_offset;  /* byte offset of ELF data from start of extra BI   */
    seL4_Word elf_size;    /* byte length of ELF image                          */
} agentos_elf_region_t;
