/* AUTO-GENERATED by tools/gen-channels/gen_channels.py — DO NOT EDIT */
/* Source: kernel/agentos-root-task/agentos.system */

#ifndef AGENTOS_CHANNELS_GENERATED_H
#define AGENTOS_CHANNELS_GENERATED_H

/* Channel IDs from agentfs perspective */
typedef enum {
    CH_AGENTFS_CONTROLLER                        = 0,
    CH_AGENTFS_EVENT_BUS                         = 1,
} agentfs_channel_t;

/* Channel IDs from app_manager perspective */
typedef enum {
    CH_APP_MANAGER_CONTROLLER                    = 0,
    CH_APP_MANAGER_SPAWN_SERVER                  = 1,
    CH_APP_MANAGER_VFS_SERVER                    = 2,
    CH_APP_MANAGER_NET_SERVER                    = 3,
    CH_APP_MANAGER_HTTP_SVC                      = 4,
} app_manager_channel_t;

/* Channel IDs from app_slot_0 perspective */
typedef enum {
    CH_APP_SLOT_0_SPAWN_SERVER                   = 0,
} app_slot_0_channel_t;

/* Channel IDs from app_slot_1 perspective */
typedef enum {
    CH_APP_SLOT_1_SPAWN_SERVER                   = 0,
} app_slot_1_channel_t;

/* Channel IDs from app_slot_2 perspective */
typedef enum {
    CH_APP_SLOT_2_SPAWN_SERVER                   = 0,
} app_slot_2_channel_t;

/* Channel IDs from app_slot_3 perspective */
typedef enum {
    CH_APP_SLOT_3_SPAWN_SERVER                   = 0,
} app_slot_3_channel_t;

/* Channel IDs from auth_server perspective */
typedef enum {
    CH_AUTH_SERVER_CONTROLLER                    = 0,
} auth_server_channel_t;

/* Channel IDs from console_mux perspective */
typedef enum {
    CH_CONSOLE_MUX_CONTROLLER                    = 0,
    CH_CONSOLE_MUX_INIT_AGENT                    = 1,
    CH_CONSOLE_MUX_EVENT_BUS                     = 2,
} console_mux_channel_t;

/* Channel IDs from controller perspective */
typedef enum {
    CH_CONTROLLER_EVENT_BUS                      = 0,
    CH_CONTROLLER_INIT_AGENT                     = 1,
    CH_CONTROLLER_AGENTFS                        = 5,
    CH_CONTROLLER_TRACE_RECORDER_0               = 6,
    CH_CONTROLLER_TRACE_RECORDER_1               = 7,
    CH_CONTROLLER_WORKER_0                       = 10,
    CH_CONTROLLER_WORKER_1                       = 11,
    CH_CONTROLLER_WORKER_2                       = 12,
    CH_CONTROLLER_WORKER_3                       = 13,
    CH_CONTROLLER_WORKER_4                       = 14,
    CH_CONTROLLER_WORKER_5                       = 15,
    CH_CONTROLLER_WORKER_6                       = 16,
    CH_CONTROLLER_WORKER_7                       = 17,
    CH_CONTROLLER_NAMESERVER                     = 18,
    CH_CONTROLLER_VFS_SERVER                     = 19,
    CH_CONTROLLER_SPAWN_SERVER                   = 20,
    CH_CONTROLLER_NET_SERVER                     = 21,
    CH_CONTROLLER_VIRTIO_BLK                     = 22,
    CH_CONTROLLER_APP_MANAGER                    = 23,
    CH_CONTROLLER_HTTP_SVC                       = 24,
    CH_CONTROLLER_PFLOCAL_SERVER                 = 26,
    CH_CONTROLLER_PROC_SERVER                    = 27,
    CH_CONTROLLER_EXEC_SERVER                    = 28,
    CH_CONTROLLER_AUTH_SERVER                    = 29,
    CH_CONTROLLER_SWAP_SLOT_0                    = 30,
    CH_CONTROLLER_SWAP_SLOT_1                    = 31,
    CH_CONTROLLER_SWAP_SLOT_2                    = 32,
    CH_CONTROLLER_SWAP_SLOT_3                    = 33,
    CH_CONTROLLER_VIBE_ENGINE                    = 40,
    CH_CONTROLLER_TIME_PARTITION                 = 41,
    CH_CONTROLLER_PERF_COUNTERS                  = 42,
    CH_CONTROLLER_TERM_SERVER                    = 43,
    CH_CONTROLLER_VM_MANAGER                     = 45,
    CH_CONTROLLER_VM_SNAPSHOT                    = 46,
    CH_CONTROLLER_EXT2FS                         = 47,
    CH_CONTROLLER_MEM_PROFILER                   = 50,
    CH_CONTROLLER_CONSOLE_MUX                    = 60,
    CH_CONTROLLER_NET_ISOLATOR                   = 61,
} controller_channel_t;

/* Channel IDs from event_bus perspective */
typedef enum {
    CH_EVENT_BUS_CONTROLLER                      = 0,
    CH_EVENT_BUS_INIT_AGENT                      = 2,
    CH_EVENT_BUS_AGENTFS                         = 6,
    CH_EVENT_BUS_WORKER_0                        = 20,
    CH_EVENT_BUS_WORKER_1                        = 21,
    CH_EVENT_BUS_WORKER_2                        = 22,
    CH_EVENT_BUS_WORKER_3                        = 23,
    CH_EVENT_BUS_WORKER_4                        = 24,
    CH_EVENT_BUS_WORKER_5                        = 25,
    CH_EVENT_BUS_WORKER_6                        = 26,
    CH_EVENT_BUS_WORKER_7                        = 27,
    CH_EVENT_BUS_CONSOLE_MUX                     = 60,
    CH_EVENT_BUS_NET_ISOLATOR                    = 61,
} event_bus_channel_t;

/* Channel IDs from exec_server perspective */
typedef enum {
    CH_EXEC_SERVER_CONTROLLER                    = 0,
} exec_server_channel_t;

/* Channel IDs from ext2fs perspective */
typedef enum {
    CH_EXT2FS_CONTROLLER                         = 0,
    CH_EXT2FS_VIRTIO_BLK                         = 1,
} ext2fs_channel_t;

/* Channel IDs from http_svc perspective */
typedef enum {
    CH_HTTP_SVC_CONTROLLER                       = 0,
    CH_HTTP_SVC_APP_MANAGER                      = 1,
} http_svc_channel_t;

/* Channel IDs from init_agent perspective */
typedef enum {
    CH_INIT_AGENT_CONTROLLER                     = 1,
    CH_INIT_AGENT_EVENT_BUS                      = 2,
    CH_INIT_AGENT_VIBE_ENGINE                    = 3,
    CH_INIT_AGENT_CONSOLE_MUX                    = 4,
    CH_INIT_AGENT_TIME_PARTITION                 = 5,
    CH_INIT_AGENT_NET_ISOLATOR                   = 6,
    CH_INIT_AGENT_NAMESERVER                     = 7,
    CH_INIT_AGENT_VFS_SERVER                     = 8,
    CH_INIT_AGENT_SPAWN_SERVER                   = 9,
    CH_INIT_AGENT_NET_SERVER                     = 10,
} init_agent_channel_t;

/* Channel IDs from mem_profiler perspective */
typedef enum {
    CH_MEM_PROFILER_CONTROLLER                   = 0,
    CH_MEM_PROFILER_WORKER_0                     = 1,
    CH_MEM_PROFILER_WORKER_1                     = 2,
    CH_MEM_PROFILER_WORKER_2                     = 3,
    CH_MEM_PROFILER_WORKER_3                     = 4,
    CH_MEM_PROFILER_WORKER_4                     = 5,
    CH_MEM_PROFILER_WORKER_5                     = 6,
    CH_MEM_PROFILER_WORKER_6                     = 7,
    CH_MEM_PROFILER_WORKER_7                     = 8,
} mem_profiler_channel_t;

/* Channel IDs from nameserver perspective */
typedef enum {
    CH_NAMESERVER_CONTROLLER                     = 0,
    CH_NAMESERVER_INIT_AGENT                     = 1,
    CH_NAMESERVER_WORKER_0                       = 2,
    CH_NAMESERVER_WORKER_1                       = 3,
    CH_NAMESERVER_WORKER_2                       = 4,
    CH_NAMESERVER_WORKER_3                       = 5,
    CH_NAMESERVER_WORKER_4                       = 6,
    CH_NAMESERVER_WORKER_5                       = 7,
    CH_NAMESERVER_WORKER_6                       = 8,
    CH_NAMESERVER_WORKER_7                       = 9,
} nameserver_channel_t;

/* Channel IDs from net_isolator perspective */
typedef enum {
    CH_NET_ISOLATOR_CONTROLLER                   = 0,
    CH_NET_ISOLATOR_INIT_AGENT                   = 1,
    CH_NET_ISOLATOR_EVENT_BUS                    = 2,
} net_isolator_channel_t;

/* Channel IDs from net_server perspective */
typedef enum {
    CH_NET_SERVER_CONTROLLER                     = 0,
    CH_NET_SERVER_INIT_AGENT                     = 1,
    CH_NET_SERVER_WORKER_0                       = 2,
    CH_NET_SERVER_WORKER_1                       = 3,
    CH_NET_SERVER_WORKER_2                       = 4,
    CH_NET_SERVER_WORKER_3                       = 5,
    CH_NET_SERVER_WORKER_4                       = 6,
    CH_NET_SERVER_WORKER_5                       = 7,
    CH_NET_SERVER_WORKER_6                       = 8,
    CH_NET_SERVER_WORKER_7                       = 9,
    CH_NET_SERVER_APP_MANAGER                    = 10,
} net_server_channel_t;

/* Channel IDs from perf_counters perspective */
typedef enum {
    CH_PERF_COUNTERS_CONTROLLER                  = 0,
    CH_PERF_COUNTERS_WORKER_0                    = 1,
    CH_PERF_COUNTERS_WORKER_1                    = 2,
    CH_PERF_COUNTERS_WORKER_2                    = 3,
    CH_PERF_COUNTERS_WORKER_3                    = 4,
    CH_PERF_COUNTERS_WORKER_4                    = 5,
    CH_PERF_COUNTERS_WORKER_5                    = 6,
    CH_PERF_COUNTERS_WORKER_6                    = 7,
    CH_PERF_COUNTERS_WORKER_7                    = 8,
} perf_counters_channel_t;

/* Channel IDs from pflocal_server perspective */
typedef enum {
    CH_PFLOCAL_SERVER_CONTROLLER                 = 0,
} pflocal_server_channel_t;

/* Channel IDs from proc_server perspective */
typedef enum {
    CH_PROC_SERVER_CONTROLLER                    = 0,
} proc_server_channel_t;

/* Channel IDs from spawn_server perspective */
typedef enum {
    CH_SPAWN_SERVER_CONTROLLER                   = 0,
    CH_SPAWN_SERVER_INIT_AGENT                   = 1,
    CH_SPAWN_SERVER_APP_MANAGER                  = 2,
    CH_SPAWN_SERVER_VFS_SERVER                   = 3,
    CH_SPAWN_SERVER_APP_SLOT_0                   = 4,
    CH_SPAWN_SERVER_APP_SLOT_1                   = 5,
    CH_SPAWN_SERVER_APP_SLOT_2                   = 6,
    CH_SPAWN_SERVER_APP_SLOT_3                   = 7,
} spawn_server_channel_t;

/* Channel IDs from swap_slot_0 perspective */
typedef enum {
    CH_SWAP_SLOT_0_CONTROLLER                    = 0,
} swap_slot_0_channel_t;

/* Channel IDs from swap_slot_1 perspective */
typedef enum {
    CH_SWAP_SLOT_1_CONTROLLER                    = 0,
} swap_slot_1_channel_t;

/* Channel IDs from swap_slot_2 perspective */
typedef enum {
    CH_SWAP_SLOT_2_CONTROLLER                    = 0,
} swap_slot_2_channel_t;

/* Channel IDs from swap_slot_3 perspective */
typedef enum {
    CH_SWAP_SLOT_3_CONTROLLER                    = 0,
} swap_slot_3_channel_t;

/* Channel IDs from term_server perspective */
typedef enum {
    CH_TERM_SERVER_CONTROLLER                    = 0,
} term_server_channel_t;

/* Channel IDs from time_partition perspective */
typedef enum {
    CH_TIME_PARTITION_CONTROLLER                 = 0,
    CH_TIME_PARTITION_WORKER_0                   = 1,
    CH_TIME_PARTITION_WORKER_1                   = 2,
    CH_TIME_PARTITION_WORKER_2                   = 3,
    CH_TIME_PARTITION_WORKER_3                   = 4,
    CH_TIME_PARTITION_WORKER_4                   = 5,
    CH_TIME_PARTITION_WORKER_5                   = 6,
    CH_TIME_PARTITION_WORKER_6                   = 7,
    CH_TIME_PARTITION_WORKER_7                   = 8,
    CH_TIME_PARTITION_INIT_AGENT                 = 9,
} time_partition_channel_t;

/* Channel IDs from trace_recorder perspective */
typedef enum {
    CH_TRACE_RECORDER_CONTROLLER_0               = 0,
    CH_TRACE_RECORDER_CONTROLLER_1               = 1,
} trace_recorder_channel_t;

/* Channel IDs from vfs_server perspective */
typedef enum {
    CH_VFS_SERVER_CONTROLLER                     = 0,
    CH_VFS_SERVER_INIT_AGENT                     = 1,
    CH_VFS_SERVER_WORKER_0                       = 2,
    CH_VFS_SERVER_WORKER_1                       = 3,
    CH_VFS_SERVER_WORKER_2                       = 4,
    CH_VFS_SERVER_WORKER_3                       = 5,
    CH_VFS_SERVER_WORKER_4                       = 6,
    CH_VFS_SERVER_WORKER_5                       = 7,
    CH_VFS_SERVER_WORKER_6                       = 8,
    CH_VFS_SERVER_WORKER_7                       = 9,
    CH_VFS_SERVER_SPAWN_SERVER                   = 10,
    CH_VFS_SERVER_APP_MANAGER                    = 11,
    CH_VFS_SERVER_VIRTIO_BLK                     = 12,
} vfs_server_channel_t;

/* Channel IDs from vibe_engine perspective */
typedef enum {
    CH_VIBE_ENGINE_INIT_AGENT                    = 0,
    CH_VIBE_ENGINE_CONTROLLER                    = 1,
} vibe_engine_channel_t;

/* Channel IDs from virtio_blk perspective */
typedef enum {
    CH_VIRTIO_BLK_CONTROLLER                     = 0,
    CH_VIRTIO_BLK_VFS_SERVER                     = 1,
    CH_VIRTIO_BLK_EXT2FS                         = 2,
} virtio_blk_channel_t;

/* Channel IDs from vm_manager perspective */
typedef enum {
    CH_VM_MANAGER_CONTROLLER                     = 0,
} vm_manager_channel_t;

/* Channel IDs from vm_snapshot perspective */
typedef enum {
    CH_VM_SNAPSHOT_CONTROLLER                    = 0,
} vm_snapshot_channel_t;

/* Channel IDs from worker_0 perspective */
typedef enum {
    CH_WORKER_0_CONTROLLER                       = 0,
    CH_WORKER_0_EVENT_BUS                        = 1,
    CH_WORKER_0_MEM_PROFILER                     = 9,
    CH_WORKER_0_PERF_COUNTERS                    = 10,
    CH_WORKER_0_TIME_PARTITION                   = 11,
    CH_WORKER_0_NAMESERVER                       = 12,
    CH_WORKER_0_VFS_SERVER                       = 13,
    CH_WORKER_0_NET_SERVER                       = 14,
} worker_0_channel_t;

/* Channel IDs from worker_1 perspective */
typedef enum {
    CH_WORKER_1_CONTROLLER                       = 0,
    CH_WORKER_1_EVENT_BUS                        = 1,
    CH_WORKER_1_MEM_PROFILER                     = 9,
    CH_WORKER_1_PERF_COUNTERS                    = 10,
    CH_WORKER_1_TIME_PARTITION                   = 11,
    CH_WORKER_1_NAMESERVER                       = 12,
    CH_WORKER_1_VFS_SERVER                       = 13,
    CH_WORKER_1_NET_SERVER                       = 14,
} worker_1_channel_t;

/* Channel IDs from worker_2 perspective */
typedef enum {
    CH_WORKER_2_CONTROLLER                       = 0,
    CH_WORKER_2_EVENT_BUS                        = 1,
    CH_WORKER_2_MEM_PROFILER                     = 9,
    CH_WORKER_2_PERF_COUNTERS                    = 10,
    CH_WORKER_2_TIME_PARTITION                   = 11,
    CH_WORKER_2_NAMESERVER                       = 12,
    CH_WORKER_2_VFS_SERVER                       = 13,
    CH_WORKER_2_NET_SERVER                       = 14,
} worker_2_channel_t;

/* Channel IDs from worker_3 perspective */
typedef enum {
    CH_WORKER_3_CONTROLLER                       = 0,
    CH_WORKER_3_EVENT_BUS                        = 1,
    CH_WORKER_3_MEM_PROFILER                     = 9,
    CH_WORKER_3_PERF_COUNTERS                    = 10,
    CH_WORKER_3_TIME_PARTITION                   = 11,
    CH_WORKER_3_NAMESERVER                       = 12,
    CH_WORKER_3_VFS_SERVER                       = 13,
    CH_WORKER_3_NET_SERVER                       = 14,
} worker_3_channel_t;

/* Channel IDs from worker_4 perspective */
typedef enum {
    CH_WORKER_4_CONTROLLER                       = 0,
    CH_WORKER_4_EVENT_BUS                        = 1,
    CH_WORKER_4_MEM_PROFILER                     = 9,
    CH_WORKER_4_PERF_COUNTERS                    = 10,
    CH_WORKER_4_TIME_PARTITION                   = 11,
    CH_WORKER_4_NAMESERVER                       = 12,
    CH_WORKER_4_VFS_SERVER                       = 13,
    CH_WORKER_4_NET_SERVER                       = 14,
} worker_4_channel_t;

/* Channel IDs from worker_5 perspective */
typedef enum {
    CH_WORKER_5_CONTROLLER                       = 0,
    CH_WORKER_5_EVENT_BUS                        = 1,
    CH_WORKER_5_MEM_PROFILER                     = 9,
    CH_WORKER_5_PERF_COUNTERS                    = 10,
    CH_WORKER_5_TIME_PARTITION                   = 11,
    CH_WORKER_5_NAMESERVER                       = 12,
    CH_WORKER_5_VFS_SERVER                       = 13,
    CH_WORKER_5_NET_SERVER                       = 14,
} worker_5_channel_t;

/* Channel IDs from worker_6 perspective */
typedef enum {
    CH_WORKER_6_CONTROLLER                       = 0,
    CH_WORKER_6_EVENT_BUS                        = 1,
    CH_WORKER_6_MEM_PROFILER                     = 9,
    CH_WORKER_6_PERF_COUNTERS                    = 10,
    CH_WORKER_6_TIME_PARTITION                   = 11,
    CH_WORKER_6_NAMESERVER                       = 12,
    CH_WORKER_6_VFS_SERVER                       = 13,
    CH_WORKER_6_NET_SERVER                       = 14,
} worker_6_channel_t;

/* Channel IDs from worker_7 perspective */
typedef enum {
    CH_WORKER_7_CONTROLLER                       = 0,
    CH_WORKER_7_EVENT_BUS                        = 1,
    CH_WORKER_7_MEM_PROFILER                     = 9,
    CH_WORKER_7_PERF_COUNTERS                    = 10,
    CH_WORKER_7_TIME_PARTITION                   = 11,
    CH_WORKER_7_NAMESERVER                       = 12,
    CH_WORKER_7_VFS_SERVER                       = 13,
    CH_WORKER_7_NET_SERVER                       = 14,
} worker_7_channel_t;

#endif /* AGENTOS_CHANNELS_GENERATED_H */
