/*
 * ringbuf.h — typed shared-memory ring buffer for agentOS PDs
 *
 * Zero-copy, lock-free SPSC (single-producer/single-consumer) ring buffer
 * suitable for seL4/Microkit shared Memory Regions.
 *
 * Design goals:
 *   - No dynamic allocation — the ring lives entirely in a caller-supplied
 *     contiguous memory region (a Microkit MR).
 *   - Lock-free SPSC: producer and consumer indices are cache-line-aligned
 *     and updated with memory barriers.  No mutexes or seL4 IPC in the
 *     fast path.
 *   - Typed: the entry type is a C struct; the ring header is separate.
 *   - Power-of-2 capacity for cheap modulo via bitmasking.
 *   - Portable: compiles for aarch64, riscv64, and x86_64.
 *
 * Usage pattern (generated by gen_ringbuf.py or written by hand):
 *
 *   // Define entry type and ring:
 *   typedef struct { uint64_t ts; uint32_t value; uint32_t tag; } MyEntry;
 *   RINGBUF_DEFINE(MyRing, MyEntry, 256)   // capacity must be power of 2
 *
 *   // Producer PD (in init()):
 *   MyRing *ring = (MyRing *)mr_vaddr;
 *   ringbuf_init_producer(&ring->hdr, sizeof(MyEntry), 256);
 *
 *   // Consumer PD (in init(), after producer):
 *   MyRing *ring = (MyRing *)mr_vaddr;
 *   ringbuf_init_consumer(&ring->hdr);   // waits for magic
 *
 *   // Enqueue (producer):
 *   MyEntry e = { .ts = now, .value = 42, .tag = 1 };
 *   ringbuf_enqueue(&ring->hdr, ring->slots, sizeof(MyEntry), &e);
 *
 *   // Dequeue (consumer):
 *   MyEntry e;
 *   if (ringbuf_dequeue(&ring->hdr, ring->slots, sizeof(MyEntry), &e)) { ... }
 *
 * Memory layout of a RINGBUF_DEFINE(Name, Entry, N) ring:
 *   [0..63]        ringbuf_hdr_t   (producer cache line)
 *   [64..127]      ringbuf_hdr_t   continuation (consumer cache line)
 *   [128..128+N*sizeof(Entry)-1]  slot array
 *
 * Copyright 2026 agentOS Project (BSD-2-Clause)
 */

#pragma once
#ifndef RINGBUF_H
#define RINGBUF_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>

/* ── Magic & version ──────────────────────────────────────────────────── */

#define RINGBUF_MAGIC   0xA05EB001UL
#define RINGBUF_VERSION 1

/* ── Memory barriers (aarch64 / riscv64 / generic) ───────────────────── */

#if defined(__aarch64__)
#  define RINGBUF_MB()   __asm__ volatile("dmb ish"   ::: "memory")
#  define RINGBUF_WMB()  __asm__ volatile("dmb ishst" ::: "memory")
#  define RINGBUF_RMB()  __asm__ volatile("dmb ishld" ::: "memory")
#elif defined(__riscv)
#  define RINGBUF_MB()   __asm__ volatile("fence rw,rw" ::: "memory")
#  define RINGBUF_WMB()  __asm__ volatile("fence w,w"   ::: "memory")
#  define RINGBUF_RMB()  __asm__ volatile("fence r,r"   ::: "memory")
#else
#  define RINGBUF_MB()   __asm__ volatile("" ::: "memory")
#  define RINGBUF_WMB()  __asm__ volatile("" ::: "memory")
#  define RINGBUF_RMB()  __asm__ volatile("" ::: "memory")
#endif

/* ── Ring header (128 bytes, two cache lines) ─────────────────────────── */

typedef struct {
    /* ── Producer cache line (bytes 0..63) ── */
    uint32_t magic;           /* RINGBUF_MAGIC */
    uint32_t version;         /* RINGBUF_VERSION */
    uint32_t capacity;        /* Number of slots (power of 2) */
    uint32_t entry_size;      /* sizeof(entry type) in bytes */
    volatile uint32_t head;   /* Producer writes here (next free slot) */
    uint8_t  _pad0[44];       /* Pad to 64 bytes */

    /* ── Consumer cache line (bytes 64..127) ── */
    volatile uint32_t tail;   /* Consumer reads from here */
    uint8_t  _pad1[60];       /* Pad to 64 bytes */
} ringbuf_hdr_t;

_Static_assert(sizeof(ringbuf_hdr_t) == 128,
               "ringbuf_hdr_t must be exactly 128 bytes");
_Static_assert(offsetof(ringbuf_hdr_t, tail) == 64,
               "ringbuf_hdr_t.tail must be on second cache line");

/* ── RINGBUF_DEFINE macro — declare a named ring type ─────────────────── */

/*
 * RINGBUF_DEFINE(Name, EntryType, Capacity)
 *
 * Declares a struct `Name` containing the header and a slot array.
 * Capacity must be a power of 2.
 *
 * Example:
 *   RINGBUF_DEFINE(PerfRing, PerfRecord, 64)
 *   // → struct PerfRing { ringbuf_hdr_t hdr; PerfRecord slots[64]; };
 */
#define RINGBUF_DEFINE(Name, EntryType, Capacity)   \
    typedef struct {                                 \
        ringbuf_hdr_t hdr;                           \
        EntryType     slots[Capacity];               \
    } Name;                                          \
    _Static_assert((Capacity) > 0 && ((Capacity) & ((Capacity)-1)) == 0, \
                   #Name ": capacity must be a power of 2")

/* ── API ──────────────────────────────────────────────────────────────── */

/*
 * Initialise the ring header on the producer side.
 * Must be called before the consumer calls ringbuf_init_consumer().
 */
static inline void ringbuf_init_producer(ringbuf_hdr_t *hdr,
                                         uint32_t entry_size,
                                         uint32_t capacity) {
    memset(hdr, 0, sizeof(ringbuf_hdr_t));
    hdr->capacity   = capacity;
    hdr->entry_size = entry_size;
    hdr->version    = RINGBUF_VERSION;
    RINGBUF_WMB();
    hdr->magic      = RINGBUF_MAGIC;  /* last write — consumer spins on this */
    RINGBUF_WMB();
}

/*
 * Initialise the ring header on the consumer side.
 * Spins until the producer has written the magic value.
 */
static inline void ringbuf_init_consumer(ringbuf_hdr_t *hdr) {
    while (1) {
        RINGBUF_RMB();
        if (hdr->magic == RINGBUF_MAGIC) break;
    }
}

/*
 * Return true if the ring header is valid (magic + version match).
 */
static inline bool ringbuf_valid(const ringbuf_hdr_t *hdr) {
    RINGBUF_RMB();
    return hdr->magic == RINGBUF_MAGIC && hdr->version == RINGBUF_VERSION;
}

/*
 * Return number of entries currently in the ring.
 */
static inline uint32_t ringbuf_count(const ringbuf_hdr_t *hdr) {
    RINGBUF_RMB();
    return hdr->head - hdr->tail;
}

/*
 * Return true if the ring is full.
 */
static inline bool ringbuf_full(const ringbuf_hdr_t *hdr) {
    RINGBUF_RMB();
    return (hdr->head - hdr->tail) >= hdr->capacity;
}

/*
 * Return true if the ring is empty.
 */
static inline bool ringbuf_empty(const ringbuf_hdr_t *hdr) {
    RINGBUF_RMB();
    return hdr->head == hdr->tail;
}

/*
 * Enqueue one entry.  `slots` is the base of the slot array.
 * Spins if the ring is full (back-pressure).
 * Returns false only if hdr is NULL or entry is NULL.
 */
static inline bool ringbuf_enqueue(ringbuf_hdr_t *hdr, void *slots,
                                   uint32_t entry_size, const void *entry) {
    if (!hdr || !slots || !entry) return false;
    /* Spin until not full */
    uint32_t head;
    do {
        RINGBUF_RMB();
        head = hdr->head;
    } while ((head - hdr->tail) >= hdr->capacity);

    uint32_t slot = head & (hdr->capacity - 1);
    uint8_t *dst = (uint8_t *)slots + (slot * entry_size);
    memcpy(dst, entry, entry_size);
    RINGBUF_WMB();
    hdr->head = head + 1;
    RINGBUF_WMB();
    return true;
}

/*
 * Try to enqueue one entry without spinning.
 * Returns true on success, false if ring is full.
 */
static inline bool ringbuf_try_enqueue(ringbuf_hdr_t *hdr, void *slots,
                                       uint32_t entry_size, const void *entry) {
    if (!hdr || !slots || !entry) return false;
    RINGBUF_RMB();
    uint32_t head = hdr->head;
    if ((head - hdr->tail) >= hdr->capacity) return false;

    uint32_t slot = head & (hdr->capacity - 1);
    memcpy((uint8_t *)slots + slot * entry_size, entry, entry_size);
    RINGBUF_WMB();
    hdr->head = head + 1;
    RINGBUF_WMB();
    return true;
}

/*
 * Dequeue one entry (non-blocking).
 * Returns true and copies into *entry if data was available.
 * Returns false if the ring is empty.
 */
static inline bool ringbuf_dequeue(ringbuf_hdr_t *hdr, void *slots,
                                   uint32_t entry_size, void *entry) {
    if (!hdr || !slots || !entry) return false;
    RINGBUF_RMB();
    uint32_t tail = hdr->tail;
    if (hdr->head == tail) return false;  /* empty */

    uint32_t slot = tail & (hdr->capacity - 1);
    memcpy(entry, (uint8_t *)slots + slot * entry_size, entry_size);
    RINGBUF_WMB();
    hdr->tail = tail + 1;
    RINGBUF_WMB();
    return true;
}

/*
 * Peek at the next entry without consuming it.
 * Returns a pointer into the slot array (valid until next dequeue).
 * Returns NULL if empty.
 */
static inline const void *ringbuf_peek(const ringbuf_hdr_t *hdr,
                                       const void *slots,
                                       uint32_t entry_size) {
    RINGBUF_RMB();
    if (hdr->head == hdr->tail) return NULL;
    uint32_t slot = hdr->tail & (hdr->capacity - 1);
    return (const uint8_t *)slots + slot * entry_size;
}

/* ── Typed convenience wrappers (use with RINGBUF_DEFINE rings) ───────── */

/*
 * RINGBUF_ENQUEUE(ring_ptr, entry_val)
 * RINGBUF_TRY_ENQUEUE(ring_ptr, entry_val)   → bool
 * RINGBUF_DEQUEUE(ring_ptr, entry_ptr)        → bool
 * RINGBUF_PEEK(ring_ptr)                      → const EntryType*
 *
 * ring_ptr must be a pointer to a ring created with RINGBUF_DEFINE.
 */
#define RINGBUF_ENQUEUE(rp, ev) \
    ringbuf_enqueue(&(rp)->hdr, (rp)->slots, \
                    sizeof((rp)->slots[0]), &(ev))

#define RINGBUF_TRY_ENQUEUE(rp, ev) \
    ringbuf_try_enqueue(&(rp)->hdr, (rp)->slots, \
                        sizeof((rp)->slots[0]), &(ev))

#define RINGBUF_DEQUEUE(rp, ep) \
    ringbuf_dequeue(&(rp)->hdr, (rp)->slots, \
                    sizeof((rp)->slots[0]), (ep))

#define RINGBUF_PEEK(rp) \
    ((const typeof((rp)->slots[0]) *) \
     ringbuf_peek(&(rp)->hdr, (rp)->slots, sizeof((rp)->slots[0])))

#define RINGBUF_INIT_PRODUCER(rp) \
    ringbuf_init_producer(&(rp)->hdr, \
                          sizeof((rp)->slots[0]), \
                          sizeof((rp)->slots) / sizeof((rp)->slots[0]))

#define RINGBUF_INIT_CONSUMER(rp) \
    ringbuf_init_consumer(&(rp)->hdr)

#define RINGBUF_VALID(rp)  ringbuf_valid(&(rp)->hdr)
#define RINGBUF_EMPTY(rp)  ringbuf_empty(&(rp)->hdr)
#define RINGBUF_FULL(rp)   ringbuf_full(&(rp)->hdr)
#define RINGBUF_COUNT(rp)  ringbuf_count(&(rp)->hdr)

#endif /* RINGBUF_H */
