use crate::GenChannelsArgs;
use anyhow::{Context, Result};
use std::collections::{BTreeMap, HashMap};
use std::fs;

fn attribute(line: &str, name: &str) -> Option<String> {
    let marker = format!("{name}=\"");
    let start = line.find(&marker)? + marker.len();
    let rest = &line[start..];
    Some(rest[..rest.find('"')?].to_string())
}

fn sanitise(name: &str) -> String {
    name.chars()
        .map(|c| match c {
            '-' | '.' => '_',
            other => other.to_ascii_uppercase(),
        })
        .collect()
}

fn generate(input: &str, source: &str) -> Result<String> {
    let mut channels: BTreeMap<String, Vec<(u32, String)>> = BTreeMap::new();
    let mut ends: Vec<(String, u32)> = Vec::new();

    for line in input.lines() {
        let line = line.trim();
        if line.starts_with("<channel") {
            ends.clear();
        } else if line.starts_with("<end ") {
            let pd = attribute(line, "pd").context("channel end is missing pd")?;
            let id = attribute(line, "id")
                .context("channel end is missing id")?
                .parse::<u32>()
                .context("channel id is not an integer")?;
            ends.push((pd, id));
        } else if line.starts_with("</channel") {
            anyhow::ensure!(
                ends.len() == 2,
                "each channel must contain exactly two ends"
            );
            let (a, a_id) = &ends[0];
            let (b, b_id) = &ends[1];
            channels
                .entry(a.clone())
                .or_default()
                .push((*a_id, b.clone()));
            channels
                .entry(b.clone())
                .or_default()
                .push((*b_id, a.clone()));
        }
    }

    let mut out = format!(
        "/* AUTO-GENERATED by `cargo xtask gen-channels` — DO NOT EDIT */\n\
         /* Source: {source} */\n\n\
         #ifndef AGENTOS_CHANNELS_GENERATED_H\n\
         #define AGENTOS_CHANNELS_GENERATED_H\n\n"
    );

    for (pd, entries) in &mut channels {
        entries.sort_by_key(|entry| entry.0);
        let mut totals: HashMap<String, usize> = HashMap::new();
        for (_, peer) in entries.iter() {
            *totals.entry(sanitise(peer)).or_default() += 1;
        }
        let mut seen: HashMap<String, usize> = HashMap::new();
        out.push_str(&format!(
            "/* Channel IDs from {pd} perspective */\n\
             typedef enum {{\n"
        ));
        for (id, peer) in entries {
            let peer = sanitise(peer);
            let suffix = if totals[&peer] > 1 {
                let index = seen.entry(peer.clone()).or_default();
                let suffix = format!("_{}", *index);
                *index += 1;
                suffix
            } else {
                String::new()
            };
            let name = format!("CH_{}_{}{}", sanitise(pd), peer, suffix);
            out.push_str(&format!("    {name:<44} = {id},\n"));
        }
        out.push_str(&format!(
            "}} {}_channel_t;\n\n",
            sanitise(pd).to_ascii_lowercase()
        ));
    }
    out.push_str("#endif /* AGENTOS_CHANNELS_GENERATED_H */\n");
    Ok(out)
}

pub fn run(args: &GenChannelsArgs) -> Result<()> {
    let input = fs::read_to_string(&args.system)
        .with_context(|| format!("failed to read {}", args.system.display()))?;
    let generated = generate(&input, &args.system.display().to_string())?;
    if let Some(parent) = args.output.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&args.output, generated)
        .with_context(|| format!("failed to write {}", args.output.display()))?;
    println!("[gen-channels] wrote {}", args.output.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_both_channel_perspectives_deterministically() {
        let xml = r#"
<system>
  <channel>
    <end pd="beta" id="2" />
    <end pd="alpha-one" id="7" />
  </channel>
</system>
"#;
        let out = generate(xml, "test.system").unwrap();
        assert!(out.contains("CH_ALPHA_ONE_BETA"));
        assert!(out.contains("CH_BETA_ALPHA_ONE"));
        assert!(out.find("alpha_one_channel_t").unwrap() < out.find("beta_channel_t").unwrap());
    }

    #[test]
    fn rejects_malformed_channels() {
        assert!(generate("<channel>\n  <end pd=\"a\" id=\"1\" />\n</channel>\n", "x").is_err());
    }
}
