#!/usr/bin/env python3
"""
gen_ringbuf.py — agentOS typed ring buffer code generator

Reads a simple YAML schema and emits a C header + optional test stub
using ringbuf.h as the runtime.

Schema format (ringbuf_schema.yaml):
  ring_name: PerfRing
  entry_type: PerfRecord
  capacity: 64          # must be power of 2
  fields:
    - name: ts
      type: uint64_t
    - name: pd_id
      type: uint8_t
    - name: latency_ns
      type: uint64_t
    - name: _pad
      type: uint8_t
      count: 7          # optional array field

  # Optional: include directives for the generated header
  includes:
    - <stdint.h>
    - <stddef.h>

  # Optional: memory region variable name (setvar_vaddr symbol)
  mr_vaddr_var: perf_ring_vaddr

Usage:
  python3 tools/gen_ringbuf.py schema.yaml [-o output.h] [--test]
  python3 tools/gen_ringbuf.py schema.yaml --validate-only

Generated output:
  - typedef struct { ... } EntryType;
  - RINGBUF_DEFINE(RingName, EntryType, Capacity)
  - static inline init/enqueue/dequeue helpers that use the mr_vaddr_var
  - Optional: a minimal test harness (--test)
"""

import sys
import os
import argparse
import math

try:
    import yaml
except ImportError:
    print("Error: pyyaml required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


# ── Helpers ────────────────────────────────────────────────────────────── #

def is_power_of_two(n: int) -> bool:
    return n > 0 and (n & (n - 1)) == 0


def c_field_line(field: dict) -> str:
    name  = field["name"]
    ftype = field["type"]
    count = field.get("count", None)
    if count is not None:
        return f"    {ftype} {name}[{count}];"
    return f"    {ftype} {name};"


def struct_size_hint(fields: list) -> str:
    """Return a human-readable size comment (approximate)."""
    known = {"uint8_t": 1, "int8_t": 1, "uint16_t": 2, "int16_t": 2,
             "uint32_t": 4, "int32_t": 4, "uint64_t": 8, "int64_t": 8,
             "float": 4, "double": 8, "bool": 1}
    total = 0
    for f in fields:
        sz = known.get(f["type"], 0)
        total += sz * f.get("count", 1)
    if total:
        return f"  // approx {total} bytes"
    return ""


# ── Validation ─────────────────────────────────────────────────────────── #

def validate(schema: dict) -> list[str]:
    errors = []
    if "ring_name" not in schema:
        errors.append("Missing required field: ring_name")
    if "entry_type" not in schema:
        errors.append("Missing required field: entry_type")
    cap = schema.get("capacity")
    if cap is None:
        errors.append("Missing required field: capacity")
    elif not isinstance(cap, int) or not is_power_of_two(cap):
        errors.append(f"capacity must be a power of 2, got: {cap}")
    fields = schema.get("fields")
    if not fields:
        errors.append("Missing required field: fields (must be non-empty list)")
    else:
        for i, f in enumerate(fields):
            if "name" not in f:
                errors.append(f"fields[{i}]: missing 'name'")
            if "type" not in f:
                errors.append(f"fields[{i}]: missing 'type'")
    return errors


# ── Code generation ────────────────────────────────────────────────────── #

def generate(schema: dict, source_yaml: str) -> str:
    ring_name   = schema["ring_name"]
    entry_type  = schema["entry_type"]
    capacity    = schema["capacity"]
    fields      = schema.get("fields", [])
    includes    = schema.get("includes", [])
    mr_var      = schema.get("mr_vaddr_var", None)
    guard       = f"{ring_name.upper()}_H"

    lines = []
    lines.append(f"/* Generated by gen_ringbuf.py from: {os.path.basename(source_yaml)} */")
    lines.append(f"/* Do not edit — regenerate with: python3 tools/gen_ringbuf.py {os.path.basename(source_yaml)} */")
    lines.append("")
    lines.append(f"#pragma once")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append('#include "ringbuf.h"')
    for inc in includes:
        lines.append(f"#include {inc}")
    lines.append("")

    # Entry struct
    hint = struct_size_hint(fields)
    # avoid nested comment (hint may contain /*...*/)
    lines.append(f"/* Ring entry: {entry_type} {hint.strip()} */")
    lines.append(f"typedef struct {{")
    for f in fields:
        lines.append(c_field_line(f))
    lines.append(f"}} {entry_type};")
    lines.append("")

    # Ring type via RINGBUF_DEFINE
    lines.append(f"/* Ring type: {ring_name} (capacity={capacity}) */")
    lines.append(f"RINGBUF_DEFINE({ring_name}, {entry_type}, {capacity});")
    lines.append("")

    # Optional MR-bound helper wrappers
    if mr_var:
        lines.append(f"/* Convenience helpers bound to {mr_var} */")
        lines.append(f"extern uintptr_t {mr_var};")
        lines.append("")
        lines.append(f"static inline {ring_name} *{ring_name.lower()}_get(void) {{")
        lines.append(f"    return ({ring_name} *)(uintptr_t){mr_var};")
        lines.append(f"}}")
        lines.append("")
        lines.append(f"static inline void {ring_name.lower()}_init_producer(void) {{")
        lines.append(f"    RINGBUF_INIT_PRODUCER({ring_name.lower()}_get());")
        lines.append(f"}}")
        lines.append("")
        lines.append(f"static inline void {ring_name.lower()}_init_consumer(void) {{")
        lines.append(f"    RINGBUF_INIT_CONSUMER({ring_name.lower()}_get());")
        lines.append(f"}}")
        lines.append("")
        lines.append(f"static inline bool {ring_name.lower()}_enqueue(const {entry_type} *e) {{")
        lines.append(f"    return RINGBUF_ENQUEUE({ring_name.lower()}_get(), *e);")
        lines.append(f"}}")
        lines.append("")
        lines.append(f"static inline bool {ring_name.lower()}_dequeue({entry_type} *e) {{")
        lines.append(f"    return RINGBUF_DEQUEUE({ring_name.lower()}_get(), e);")
        lines.append(f"}}")
        lines.append("")

    lines.append(f"#endif /* {guard} */")
    return "\n".join(lines) + "\n"


def generate_test(schema: dict) -> str:
    ring_name  = schema["ring_name"]
    entry_type = schema["entry_type"]
    capacity   = schema["capacity"]

    lines = []
    lines.append(f"/* Auto-generated test stub for {ring_name} */")
    lines.append(f'#include "{ring_name.lower()}.h"')
    lines.append('#include <stdio.h>')
    lines.append('#include <assert.h>')
    lines.append('#include <string.h>')
    lines.append("")
    lines.append(f"static {ring_name} g_ring;")
    lines.append("")
    lines.append("int main(void) {")
    lines.append(f"    RINGBUF_INIT_PRODUCER(&g_ring);")
    lines.append(f"    assert(RINGBUF_VALID(&g_ring));")
    lines.append(f"    assert(RINGBUF_EMPTY(&g_ring));")
    lines.append(f"    assert(!RINGBUF_FULL(&g_ring));")
    lines.append("")
    lines.append(f"    /* Fill ring to capacity */")
    lines.append(f"    for (int i = 0; i < {capacity}; i++) {{")
    lines.append(f"        {entry_type} e;")
    lines.append(f"        memset(&e, 0, sizeof(e));")
    lines.append(f"        assert(RINGBUF_TRY_ENQUEUE(&g_ring, e));")
    lines.append(f"    }}")
    lines.append(f"    assert(RINGBUF_FULL(&g_ring));")
    lines.append(f"    assert(!RINGBUF_TRY_ENQUEUE(&g_ring, ({entry_type}){{0}}));")
    lines.append("")
    lines.append(f"    /* Drain ring */")
    lines.append(f"    int dequeued = 0;")
    lines.append(f"    {entry_type} out;")
    lines.append(f"    while (RINGBUF_DEQUEUE(&g_ring, &out)) dequeued++;")
    lines.append(f"    assert(dequeued == {capacity});")
    lines.append(f"    assert(RINGBUF_EMPTY(&g_ring));")
    lines.append("")
    lines.append(f"    printf(\"{ring_name} test passed (capacity=%d)\\n\", {capacity});")
    lines.append(f"    return 0;")
    lines.append("}")
    return "\n".join(lines) + "\n"


# ── Main ───────────────────────────────────────────────────────────────── #

def main():
    parser = argparse.ArgumentParser(
        description="agentOS ring buffer code generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__)
    parser.add_argument("schema", help="YAML schema file")
    parser.add_argument("-o", "--output", default=None,
                        help="Output .h file (default: <ring_name>.h in same dir)")
    parser.add_argument("--test", action="store_true",
                        help="Also emit a test stub <ring_name>_test.c")
    parser.add_argument("--validate-only", action="store_true",
                        help="Validate schema and exit without writing files")
    args = parser.parse_args()

    with open(args.schema) as f:
        schema = yaml.safe_load(f)

    errors = validate(schema)
    if errors:
        for e in errors:
            print(f"  ✗ {e}", file=sys.stderr)
        sys.exit(1)

    if args.validate_only:
        cap = schema["capacity"]
        print(f"✓ Schema valid: {schema['ring_name']} / {schema['entry_type']} / capacity={cap}")
        return

    code = generate(schema, args.schema)

    out_path = args.output
    if not out_path:
        out_dir  = os.path.dirname(os.path.abspath(args.schema))
        out_path = os.path.join(out_dir, f"{schema['ring_name'].lower()}.h")

    with open(out_path, "w") as f:
        f.write(code)
    print(f"✓ Generated: {out_path}")

    if args.test:
        test_code = generate_test(schema)
        test_path = out_path.replace(".h", "_test.c")
        with open(test_path, "w") as f:
            f.write(test_code)
        print(f"✓ Test stub:  {test_path}")
        print(f"  Compile with: gcc -std=c11 -I. {os.path.basename(test_path)} -o test_{schema['ring_name'].lower()}")


if __name__ == "__main__":
    main()
