# Old generated .d files can name the previous main source path.
# Empty prerequisites allow the real relocated source rule to rebuild them.
PD_MIGRATION_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))
src/agent_pool.c $(PD_MIGRATION_ROOT)/src/agent_pool.c:
src/app_manager.c $(PD_MIGRATION_ROOT)/src/app_manager.c:
src/app_slot.c $(PD_MIGRATION_ROOT)/src/app_slot.c:
src/auth_server.c $(PD_MIGRATION_ROOT)/src/auth_server.c:
src/block_pd.c $(PD_MIGRATION_ROOT)/src/block_pd.c:
src/boot_integrity.c $(PD_MIGRATION_ROOT)/src/boot_integrity.c:
src/cap_broker.c $(PD_MIGRATION_ROOT)/src/cap_broker.c:
src/cap_policy.c $(PD_MIGRATION_ROOT)/src/cap_policy.c:
src/cc_pd.c $(PD_MIGRATION_ROOT)/src/cc_pd.c:
src/cc_retry_cache.c $(PD_MIGRATION_ROOT)/src/cc_retry_cache.c:
src/cc_vm_client.c $(PD_MIGRATION_ROOT)/src/cc_vm_client.c:
src/ed25519_verify.c $(PD_MIGRATION_ROOT)/src/ed25519_verify.c:
src/exec_server.c $(PD_MIGRATION_ROOT)/src/exec_server.c:
src/ext2fs.c $(PD_MIGRATION_ROOT)/src/ext2fs.c:
src/fault_handler.c $(PD_MIGRATION_ROOT)/src/fault_handler.c:
src/fault_inject.c $(PD_MIGRATION_ROOT)/src/fault_inject.c:
src/fdt_builder.c $(PD_MIGRATION_ROOT)/src/fdt_builder.c:
src/framebuffer_pd.c $(PD_MIGRATION_ROOT)/src/framebuffer_pd.c:
src/gpu_sched.c $(PD_MIGRATION_ROOT)/src/gpu_sched.c:
src/gpu_shmem.c $(PD_MIGRATION_ROOT)/src/gpu_shmem.c:
src/guest_vmm.c $(PD_MIGRATION_ROOT)/src/guest_vmm.c:
src/http_svc.c $(PD_MIGRATION_ROOT)/src/http_svc.c:
src/init_agent.c $(PD_MIGRATION_ROOT)/src/init_agent.c:
src/irq_pd.c $(PD_MIGRATION_ROOT)/src/irq_pd.c:
src/log_drain.c $(PD_MIGRATION_ROOT)/src/log_drain.c:
src/lwip_shim.c $(PD_MIGRATION_ROOT)/src/lwip_shim.c:
src/lwip_sys.c $(PD_MIGRATION_ROOT)/src/lwip_sys.c:
src/mem_profiler.c $(PD_MIGRATION_ROOT)/src/mem_profiler.c:
src/monitor.c $(PD_MIGRATION_ROOT)/src/monitor.c:
src/monocypher.c $(PD_MIGRATION_ROOT)/src/monocypher.c:
src/nameserver.c $(PD_MIGRATION_ROOT)/src/nameserver.c:
src/native_net_client.c $(PD_MIGRATION_ROOT)/src/native_net_client.c:
src/net_isolator.c $(PD_MIGRATION_ROOT)/src/net_isolator.c:
src/pd_entry.c $(PD_MIGRATION_ROOT)/src/pd_entry.c:
src/perf_counters.c $(PD_MIGRATION_ROOT)/src/perf_counters.c:
src/pflocal_server.c $(PD_MIGRATION_ROOT)/src/pflocal_server.c:
src/proc_server.c $(PD_MIGRATION_ROOT)/src/proc_server.c:
src/sha256_mini.c $(PD_MIGRATION_ROOT)/src/sha256_mini.c:
src/smc_stub.c $(PD_MIGRATION_ROOT)/src/smc_stub.c:
src/snapshot_sched.c $(PD_MIGRATION_ROOT)/src/snapshot_sched.c:
src/spawn_server.c $(PD_MIGRATION_ROOT)/src/spawn_server.c:
src/swap_slot.c $(PD_MIGRATION_ROOT)/src/swap_slot.c:
src/term_server.c $(PD_MIGRATION_ROOT)/src/term_server.c:
src/time_partition.c $(PD_MIGRATION_ROOT)/src/time_partition.c:
src/timer_pd.c $(PD_MIGRATION_ROOT)/src/timer_pd.c:
src/trace_recorder.c $(PD_MIGRATION_ROOT)/src/trace_recorder.c:
src/usb_pd.c $(PD_MIGRATION_ROOT)/src/usb_pd.c:
src/verify.c $(PD_MIGRATION_ROOT)/src/verify.c:
src/vfs_server.c $(PD_MIGRATION_ROOT)/src/vfs_server.c:
src/vibe_swap.c $(PD_MIGRATION_ROOT)/src/vibe_swap.c:
src/virtio_blk.c $(PD_MIGRATION_ROOT)/src/virtio_blk.c:
src/vm_manager.c $(PD_MIGRATION_ROOT)/src/vm_manager.c:
src/vm_snapshot.c $(PD_MIGRATION_ROOT)/src/vm_snapshot.c:
src/vmm_mux_stub.c $(PD_MIGRATION_ROOT)/src/vmm_mux_stub.c:
src/wasm3_host.c $(PD_MIGRATION_ROOT)/src/wasm3_host.c:
src/wg_net.c $(PD_MIGRATION_ROOT)/src/wg_net.c:
src/worker.c $(PD_MIGRATION_ROOT)/src/worker.c:
